# action.yml
name: 'deb-checker'
description: 'Test build of a debian package with additional checks'
inputs:
  err-on-lint:
    description: 'fail on all lintian outputs'
    required: false
    default: 'false'
outputs:
  lint:
    description: 'lintian status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.err-on-lint }}
