# action.yml
name: 'deb-checker'
description: 'Test build of a debian package with additional checks'
outputs:
  debversion:
    description: 'debian package version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.err-on-lint }}
